spring:
  cloud:
    config:
      server:
        git:
          # 配置服务器获取git本地资源地址
          uri: https://github.com/ycxzuo/configuration.git
#          username: ***
#          password: ***
          search-paths: config
    bus:
      refresh:
        enabled: true
  # 配置服务器名称
  application:
    name: config-server
  kafka:
    bootstrap-servers: 47.106.80.100:9092
    consumer:
      group-id: springCloudBus

# 配置服务器的端口
server:
  port: 7071

management:
  endpoints:`
    web:
      base-path: /actuator  # 访问根路径
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/