server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: ribbon-demo

logging:
  level:
    root: WARN
    org.springframework.web: trace


management:
  endpoints:
    web:
      base-path: /actuator  # 访问根路径
      exposure:
        include: "*"