logging:
  level:
    # root: info
    # org.mybatis: debug
    # java.sql: debug
    org.springframework.web: trace

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics
  endpoint:
    shutdown:
      enabled: false

server:
  port: 8071
