# mybatis-plus 配置
mybatis-plus:
  configuration:
    # 输出 sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置 mapper 的路径
  mapper-locations: classpath*:/com/yczuoxin/demo/eurekaclient2/mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082

spring:
  application:
    name: eureka-client

logging:
  level:
    root: DEBUG

management:
  endpoints:
    web:
      base-path: /actuator  # 访问根路径
      exposure:
        include: "*"