# 启动端口
server:
  port: 8081

# 服务名称
spring:
  application:
    name: eureka-client

# 注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  # 点击Eureka页面的链接的IP值
  instance:
    hostname: clientName

