eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/

server:
  port: 6060

spring:
  application:
    name: feign-client

logging:
  level:
    root: WARN
    org.springframework.web: trace

feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true