spring:
  cloud:
    bus:
      enabled: true
  kafka:
    bootstrap-servers: 47.106.80.100:9092

management:
  endpoints:
    web:
      base-path: /actuator  # 访问根路径
      exposure:
        include: "*"